Added logo to coverpage
latextemplates/scientific-thesis-cover pull request #28
Opened 2022-01-21 14:10 UTC by halachtm

Added the ability to add a logo at the very top of the coverpage.

## Changes
Adding the logo is optional. If a logo is added the institute is moved down a bit but nothing else. If no logo is added the institute remains were it was before this change.

`demo.txt` was updated to show this is an option now. For this the logo of the University of Stuttgart is now included in the repo.

## Reasons
This change was done to make this template conform to the [layout requirements](https://www.f05.uni-stuttgart.de/en/cs/students/thesis/) of the CS faculty of the University of Stuttgart. The logo is made optional as to not interfere with other institutions using this template.

## Points to consider
- The `graphicx` package is only included if a logo is specified.
- The image's path can not contain any underscores because `kvoptions` interprets them as `Ω_` if they are escaped or as the LaTeX subscript operator if they are not escaped.

---

- [x] Change in CHANGELOG.md described

2022-01-23 14:40 UTC, Vogel612 requested changes
Please ensure that you are consistently indenting your changes with spaces (as in the rest of the sourcefile is indented)

2022-01-25 10:55 UTC, halachtm commented
I have removed all tabs from scientific-thesis-cover.sty and indented with 4 spaces. There were already tabs in demo.tex, so to keep it consistent I kept the tab indentation of my new line.

2022-02-03 21:19 UTC, koppor commented
What is the license of [logo/unistuttgartlogoenglish.png](https://github.com/latextemplates/scientific-thesis-cover/pull/28/files#diff-fb15f3cb27dc25f8c577402253763c3f243613abf129ed125c84c5340811ee72)?

I think, it could be better to use the example images of [mwe](https://ctan.org/pkg/mwe?lang=de). Jsut replace the png by `example-image-16x9.pdf`. (and add `\usepackage{mwe}` to `demo.tex`)

2022-02-10 11:15 UTC, halachtm commented
I forgot to consider the licensing rights -_-
I have replaced it with mwe now like you suggested.

2023-03-20 21:49 UTC, koppor commented
Thank you for the update! I'll merge.

In future, please spell "cannot" :) - I'll fix sometime in the future.

2023-03-20 21:49 UTC, merged